In [30]:
import parse as pr
import pandas as pd

### Khairul Irfan

In [7]:
import parse as pr
import pandas as pd

simple_log_data = [
    "INFO [2023-05-17 12:34:56.789] This is a simple log message",
    "ERROR [2023-05-18 01:23:45.678] An error occurred",
    "WARNING [2023-05-19 10:20:30.123] This is a warning message"
]

formatt="{type} [{date}] {message}" 

collection=[]
for line in simple_log_data:
    parsed=pr.parse(formatt,line).named
    collection.append(parsed)

pd.DataFrame(collection)

      type                     date                       message
0     INFO  2023-05-17 12:34:56.789  This is a simple log message
1    ERROR  2023-05-18 01:23:45.678             An error occurred
2  WARNING  2023-05-19 10:20:30.123     This is a warning message

### Testing

In [60]:
import parse 
import pandas as pd

In [82]:
log_format="{timestamp}  {duration} {type} {details}"

with open('study_parse_log/LCS0001.LOG', 'r') as log_file:
    log_file_lines= log_file.readlines()

log_collection = []

for line in log_file_lines:
    parsed = parse.parse(log_format,line)
    log_collection.append(parsed.named)

FileNotFoundError: [Errno 2] No such file or directory: 'study_parse_log/LCS0001.LOG'

In [83]:
df = pd.DataFrame(log_collection)
df

,timestamp,duration,type,details
0,2024-06-28T15:32:42.672,0.00000,TFI,< >< >< >\n
1,2024-06-28T15:32:42.680,8.07220,SEN,<LTL 0><ALB 0><OTL 0><MLB 0><PSN 0><PSG 0><FSW...
2,2024-06-28T15:32:42.726,45.15410,VDC,Bounded\n
3,2024-06-28T15:33:03.763,21.03695s,APR,Enlist [PUTRAJAYA5555 ][470M669NWA7R1X32 ...
4,2024-06-28T15:33:03.763,0.07810,REC,<QID 3B9ACA01><PSN F><PSG _><TRX S=SE V=INI E=...
5,2024-06-28T15:33:03.763,0.18260,VDC,"Select [1:1,0][470M669NWA7R1X32 ] 0 -> 0\n"
6,2024-06-28T15:33:03.763,0.00000,TFI,<1 >< >< >\n
7,2024-06-28T15:33:03.767,3.73560,SEN,<LTL 0><ALB 0><OTL 0><MLB 0><PSN 0><PSG 0><FSW...
8,2024-06-28T15:33:08.767,5.00071s,SEN,<LTL 0><ALB 0><OTL 0><MLB 0><PSN 0><PSG 0><FSW...
9,2024-06-28T15:33:26.251,17.48340s,RES,<QID 3B9ACA01><PSN F><PSG _><TRX S=OK V=EXM E=...
10,2024-06-28T15:33:26.254,3.18260,APR,Select [PUTRAJAYA5555 ][470M669NWA7R1X32 ...
11,2024-06-28T15:33:26.254,0.12820,TFI,<1 ><SELAMAT ><JALAN >\n
12,2024-06-28T15:33:26.259,5.48120,SEN,<LTL 1><ALB 0><OTL 0><MLB 0><PSN 0><PSG 0><FSW...
13,2024-06-28T15:33:27.717,1.45763s,REM,<QID 3B9ACA01><PSN F><PSG _><TRX S=OK V=EXM E=...
14,2024-06-28T15:33:27.717,0.00000,TFI,< >< >< >\n
15,2024-06-28T15:33:27.719,1.65430,SEN,<LTL 0><ALB 0><OTL 0><MLB 0><PSN 0><PSG 0><FSW...
16,2024-06-28T15:33:37.401,9.68267s,REC,<QID 3B9ACA02><PSN F><PSG _><TRX S=SE V=INI E=...
17,2024-06-28T15:33:37.401,0.00000,TFI,<2 >< >< >\n
18,2024-06-28T15:33:37.410,8.39830,SEN,<LTL 0><ALB 0><OTL 0><MLB 0><PSN 0><PSG 0><FSW...
19,2024-06-28T15:33:38.642,1.23219s,RES,<QID 3B9ACA02><PSN F><PSG _><TRX S=OK V=EXM E=...
20,2024-06-28T15:33:38.642,0.00000,TFI,<2 ><SELAMAT ><JALAN >\n
21,2024-06-28T15:33:38.646,3.72120,SEN,<LTL 1><ALB 0><OTL 0><MLB 0><PSN 0><PSG 0><FSW...
22,2024-06-28T15:33:40.247,1.60108s,REM,<QID 3B9ACA02><PSN F><PSG _><TRX S=OK V=EXM E=...
23,2024-06-28T15:33:40.247,0.00000,TFI,< >< >< >\n
24,2024-06-28T15:33:40.252,5.35940,SEN,<LTL 0><ALB 0><OTL 0><MLB 0><PSN 0><PSG 0><FSW...
25,2024-06-28T15:34:06.143,25.89064s,REC,<QID 3B9ACA03><PSN F><PSG _><TRX S=SE V=INI E=...
26,2024-06-28T15:34:06.143,0.00000,TFI,<3 >< >< >\n
27,2024-06-28T15:34:06.156,13.51320,SEN,<LTL 0><ALB 0><OTL 0><MLB 0><PSN 0><PSG 0><FSW...
28,2024-06-28T15:34:07.056 899.39230,APR,Enlist,[PUTRAJAYA5555 ][470M669NWA7R1X33 ] 0 -> 1\n
29,2024-06-28T15:34:07.056,0.05300,VDC,"Select [2:2,0][470M669NWA7R1X33 ] 0 -> 0\n"
30,2024-06-28T15:34:11.158,4.10230s,SEN,<LTL 0><ALB 0><OTL 0><MLB 0><PSN 0><PSG 0><FSW...
31,2024-06-28T15:34:12.292,1.13422s,RES,<QID 3B9ACA03><PSN F><PSG _><TRX S=OK V=EXM E=...
32,2024-06-28T15:34:12.293,0.88390,APR,Select [PUTRAJAYA5555 ][470M669NWA7R1X33 ...
33,2024-06-28T15:34:12.293,0.04050,TFI,<3 ><SELAMAT ><JALAN >\n
34,2024-06-28T15:34:12.296,2.67140,SEN,<LTL 1><ALB 0><OTL 0><MLB 0><PSN 0><PSG 0><FSW...
35,2024-06-28T15:34:13.407,1.11115s,REM,<QID 3B9ACA03><PSN F><PSG _><TRX S=OK V=EXM E=...
36,2024-06-28T15:34:13.407,0.00000,TFI,< >< >< >\n
37,2024-06-28T15:34:13.409,1.66430,SEN,<LTL 0><ALB 0><OTL 0><MLB 0><PSN 0><PSG 0><FSW...